/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: moham
 *
 * Created on September 24, 2023, 4:47 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H

#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURES_ENABLE   1U
//#define INTERRUPT_PRIORITY_LEVELS_ENABLE                    INTERRUPT_FEATURES_ENABLE
#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE              INTERRUPT_FEATURES_ENABLE
#define EXTERNAL_INTERRUPT_OnChange_FEATURE_ENABLE          INTERRUPT_FEATURES_ENABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

